<a href="https://colab.research.google.com/github/vedantsaraf2002/IITMCodes/blob/main/MatrixMultiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MATRIX MULTIPLICATION

C[i][j] is the dot product of the ith row of A and the jth column of B.

In [5]:
  dim=4

  r1 = [1,2,3,4]
  r2 = [4,5,6,7]
  r3 = [7,8,9,10]
  r4 = [11,12,13,14]

  s1 = [1,2,1,2]
  s2 = [6,2,3,15]
  s3 = [4,2,1,45]
  s4 = [1,7,2,9] 

  A=[]
  A.append(r1)
  A.append(r2)
  A.append(r3)
  A.append(r4)

  B=[]
  B.append(s1)
  B.append(s2)
  B.append(s3)
  B.append(s4)
  
  C=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
  
  for i in range(dim):
    for j in range(dim):
       for k in range(dim):
          C[i][j] = C[i][j] + A[i][k] * B[k][j]
  print(C)

[[29, 40, 18, 203], [65, 79, 39, 416], [101, 118, 60, 629], [149, 170, 88, 913]]


Shortcut of Matrix Multiplication using NUMPY

In [8]:
import numpy
X=numpy.mat(A)
Y=numpy.mat(B)
print(X*Y)

[[ 29  40  18 203]
 [ 65  79  39 416]
 [101 118  60 629]
 [149 170  88 913]]
